[package]
name = "text-search-derive"
version = "0.6.0"
edition = "2024"
description = "Derive macro for text-search crate"
homepage = "https://github.com/Salman-Sali/text-search"
license = "MIT"


[lib]
proc-macro = true

[dependencies]
darling = "0.20"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.89"
text-search-core = { workspace = true }
